### ISSUE TITLE
Unsupported

### ISSUE THREAD

**Issue by Akianonymus** [Oreo-Harpia/android_device_motorola_msm8916-common#2]
https://github.com/Oreo-Harpia/android_device_motorola_msm8916-common/blob/5be90678fe4d5b831077ea3a5c385c5a59c48383/msm8916.mk#L119

see here
https://github.com/LineageOS/android_device_cyanogen_msm8916-common/commit/ffa1080c70b994d549d4e979f47cb3b0eab451f8

**Comment by Akianonymus** [comment]
This too

https://github.com/LineageOS/android_device_cyanogen_msm8916-common/commit/23b034c9b338f5e13ab1dd23c93eff35c85998a2

**Comment by SubhrajyotiSen** [comment]
Commits have been pushed

**Comment by Akianonymus** [comment]
What about the other one??

**Comment by SubhrajyotiSen** [comment]
I dropped it long ago
https://github.com/Oreo-Harpia/android_device_motorola_msm8916-common/commit/0324450abc9dbd0da0e0323daa80e2b36004cede
